### ISSUE TITLE
Decimal to roman

### ISSUE THREAD

**Issue by IonicaBizau** [mcandre/node-roman#2]
Would be nice to have a function to convert decimal to roman numbers. :smile:

**Comment by mcandre** [comment]
Pull requests appreciated :) Would you like to try? Just be sure to add several tests to the test suite.

**Comment by IonicaBizau** [comment]
Currently I'm busy with projects... But if I will need it some day, I will create a pr. :smile:

**Comment by mcandre** [comment]
Closing the ticket for now. Feel free to submit a pull request if you have time.
